/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

//import com.sun.awt.AWTUtilities;
import Clases.HiloRotar;
import Clases.Recursos;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

//import java.awt.Color;
public class FrmPrincipal extends javax.swing.JFrame implements Runnable {

    private Thread hilo1, hilo2;
    HiloSonido playSonidoInicial;
    HiloSonido playBoton;
    Player player;
    
    Recursos tools=new Recursos();
    //private int velocidad = 10, x = 280, y = 120;
    private int x = 1080, y = 1920;

    public FrmPrincipal() {
        this.setUndecorated(true);
        initComponents();
        playSonidoInicial = new HiloSonido("SonidoInicial.mp3", true);
        this.setSize(x, y);
        this.setLocationRelativeTo(null);
        this.setIconImage(tools.setIcono().getImage());
        btnTest.setVisible(false);
        //this.setOpacity(0.4f);
        //AWTUtilities.setWindowOpaque(this, false);
        //btnTest.setOpaque(false);
        //btnTest.setContentAreaFilled(true);
        //btnTest.setBorderPainted(false);
        //this.setResizable(false);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(240, 23, 226));
        setPreferredSize(new java.awt.Dimension(1080, 1920));
        setSize(new java.awt.Dimension(1080, 1920));
        getContentPane().setLayout(null);

        btnTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPrincipalGif.gif"))); // NOI18N
        btnTest.setBorder(null);
        btnTest.setBorderPainted(false);
        btnTest.setContentAreaFilled(false);
        btnTest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTest.setPreferredSize(null);
        btnTest.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPrincipalGif.gif"))); // NOI18N
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        getContentPane().add(btnTest);
        btnTest.setBounds(110, 460, 810, 1130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bgPrincipalSolo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 1920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        // playSong();
        playBoton = new HiloSonido("SonidoClick.mp3", false);
        playSonidoInicial.close();
        new FrmRuletaRueda().show();
        this.dispose();

    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmPrincipal().setVisible(true);
                new Thread(new FrmPrincipal()).start();
            }
        });
    }

    public void run() {
        try {
            this.setVisible(true);
            /*for (int i = 0; i < 9; i++) {
             hilo1.sleep(velocidad);
             this.setSize(x, y);
             this.setLocationRelativeTo(null);
             x = x + 100;
             //  System.out.println(this.getSize().width);

             if (x == 1080) {
             for (int j = 0; j < 76; j++) {
             hilo2.sleep(velocidad);
             this.setSize(x, y);
             this.setLocationRelativeTo(null);
             y = y + 25;
             System.out.println(this.getSize().height);
             }
             } 
             }*/
            btnTest.setVisible(true);
        } catch (Exception e) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
