/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.sun.awt.AWTUtilities;
import java.awt.Color;


/**
 *
 * @author 4ser
 */
public class FrmPrincipal extends javax.swing.JFrame  implements Runnable{

    private Thread hilo1, hilo2;
    private int velocidad = 10, x = 280, y = 120;
    
    public FrmPrincipal() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(x, y);
        this.setLocationRelativeTo(null);
        btnTest.setVisible(false);
        //this.setOpacity(0.4f);
        AWTUtilities.setWindowOpaque(this, false);
        //btnTest.setOpaque(false);
        //btnTest.setContentAreaFilled(true);
        //btnTest.setBorderPainted(false);
        //this.setResizable(false);

    }

    private void playSong() {
        HiloSonido play=new HiloSonido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(240, 23, 226));
        setPreferredSize(new java.awt.Dimension(1080, 1920));
        getContentPane().setLayout(null);

        btnTest.setText("Test");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });
        getContentPane().add(btnTest);
        btnTest.setBounds(290, 930, 410, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bgnMain.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 1920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        //playSong();
        this.dispose();
        new Thread(new FrmRuleta()).start();
    }//GEN-LAST:event_btnTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmPrincipal().setVisible(true);
                new Thread(new FrmPrincipal()).start();
            }
        });
    }
    
    public void run(){
        try {
            this.setVisible(true);
            for (int i = 0; i < 9; i++) {
                hilo1.sleep(velocidad);
                this.setSize(x, y);
                this.setLocationRelativeTo(null);
                x = x + 100;
              //  System.out.println(this.getSize().width);

                if (x == 1080) {
                    for (int j = 0; j < 76; j++) {
                        hilo2.sleep(velocidad);
                        this.setSize(x, y);
                        this.setLocationRelativeTo(null);
                        y = y + 25;
                        System.out.println(this.getSize().height);
                    }
                } 
            }
            btnTest.setVisible(true);
        } catch (Exception e) {

        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
